### ISSUE TITLE
Replace yaml-rust with serde_yaml 

### ISSUE THREAD

**Issue by Ichmed** [Elektrobit/flake-pilot#128]
Right now the config in both pilots is being parsed into a generic Yaml node that is evaluated on the fly. This may cause destructive actions to be performed before terminating the program due to a faulty config.

By parsing deserializing the config into a fixed struct the pilot can quit on startup if the config is invalid. This will also prevent errors due to typos and make the config more discoverable for new contributors.

**Comment by schaefi** [comment]
We are complete here imho. Thanks much for the effort
