### ISSUE TITLE
Registering a non existing container

### ISSUE THREAD

**Issue by Ichmed** [Elektrobit/flake-pilot#144]
Right now it is possible to register a podman container that is not present on the host e.g.
`sudo flake-ctl podman register --container ThisContainerDoesNotExist --app /usr/bin/Nothing --target /`

@schaefi @m-kat Is this intended? I would assume the command to fail because the container is not present or otherwise try to pull the container and then fail because it does not exist.

**Comment by schaefi** [comment]
The behavior is intended for the podman-pilot because podman automatically fetches containers which doesn't exist on the system at call time.

For the firecracker pilot we exit with an error if the vm to use is not available
