### ISSUE TITLE
man page missing for sci

### ISSUE THREAD

**Issue by schaefi** [Elektrobit/flake-pilot#78]
# Description

There is currently no man page for /usr/sbin/sci

# Acceptance Criteria

man page exists

**Comment by wintron04** [comment]
created first draft of a man page for sci, called guestvm-tools-sci

**Comment by schaefi** [comment]
@wintron04 nice, if in doubt you can also always create a draft PR for early review. Regarding the name of the man page that should be available by the name of the binary. So the binary name for sci is ```sci``` thus I suggest the man page should be named ```sci``` such that ```man sci``` gives us something

**Comment by wintron04** [comment]
@schaefi Makes sense, changed it.
